# simulate a failing test
import sys

sys.exit(1)